catalog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', views.LoanedBooksAllListView.as_view(), name='all-borrowed'),
]

minimallibrary/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('catalog/', include('catalog.urls')),
                  path('', RedirectView.as_view(url='catalog/', permanent=True)),
                  path('accounts/', include('django.contrib.auth.urls'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = "Library Admin"
admin.site.site_title = "Library Admin Portal"
admin.site.index_title = "Welcome to Minimal Library Portal"

catalog/models.py
import uuid  # Required for unique book instances
from datetime import date

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.
class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(
        max_length=32
    )

    class Meta:
        ordering = ['name']

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=256)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file
    author = models.ForeignKey(
        'Author',
        on_delete=models.SET_NULL,
        null=True
    )
    """
    By default on_delete=models.CASCADE,
    which means that if the author was deleted,
    this book would be deleted too!
    We use SET_NULL here,
    but we could also use PROTECT or RESTRICT
    to prevent the author being deleted while any book uses it.
    """
    summary = models.TextField(
        max_length=1024
    )

    isbn = models.CharField(
        max_length=13,
        unique=True,
        verbose_name='ISBN'
    )

    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(
        Genre
    )

    # language foreign key
    language = models.ForeignKey(
        'Language',
        on_delete=models.SET_NULL,
        null=True
    )

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        # e.g. .../book-detail/2
        # add proper url-to-view mapping
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4
    )

    borrower = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    book = models.ForeignKey(
        'Book',
        on_delete=models.RESTRICT,
        null=True
    )

    imprint = models.CharField(max_length=256)

    due_back = models.DateField(
        null=True,
        blank=True
    )

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m'
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)

    date_of_birth = models.DateField(
        null=True,
        blank=True
    )

    date_of_death = models.DateField(
        'Died',
        null=True,
        blank=True
    )

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'


# FIXME CharField or TextField should use '' instead of NULL
# https://stackoverflow.com/a/44272461

class Language(models.Model):
    """Model representing a language."""
    name = models.CharField(
        max_length=32
    )

    """String for representing the Model object."""

    def __str__(self):
        return self.name

catalog/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from .models import Book, Author, BookInstance


def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


class BookListView(generic.ListView):
    model = Book
    paginate_by = 5


class BookDetailView(generic.DetailView):
    model = Book


class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 5


class AuthorDetailView(generic.DetailView):
    model = Author


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


class LoanedBooksAllListView(PermissionRequiredMixin, generic.ListView):
    """Generic class-based view listing all books on loan. Only visible to users with can_mark_returned permission."""
    model = BookInstance
    permission_required = 'catalog.can_mark_returned'
    template_name = 'catalog/bookinstance_list_borrowed_all.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Minimal Library</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
                <hr>
                <ul class="sidebar-nav">
                    <li><a href="/admin">Admin Portal</a></li>
                </ul>
                <hr>
                <ul class="sidebar-nav">
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'books' %}">All books</a></li>
                    <li><a href="{% url 'authors' %}">All authors</a></li>
                </ul>

                <ul class="sidebar-nav">
                    <hr>
                    {% if user.is_authenticated %}
                        <li>You: {{ user.get_username }}</li>
                        <li><a href="{% url 'my-borrowed' %}">My Borrowed</a></li>
                        <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
                    {% endif %}
                </ul>

                <ul class="sidebar-nav">
                    <hr>
                    {% if user.is_staff %}
                        <li>Staff</li>
                        {% if perms.catalog.can_mark_returned %}
                            <li><a href="{% url 'all-borrowed' %}">All borrowed</a></li>
                        {% endif %}
                    {% endif %}
                </ul>
            {% endblock %}
        </div>
        <div class="col-sm-10 ">{% block content %}{% endblock %}{% block pagination %}
            {% if is_paginated %}
                <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
                </div>
            {% endif %}
        {% endblock %}</div>
    </div>
</div>
</body>
</html>

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block title %}
	<title>Author detail</title>
{% endblock %}

{% block content %}
	<h1>{{ author }}</h1>
	<p class="text-muted">{% if author.date_of_birth %}{{ author.date_of_birth }}{% endif %} -
		{% if author.date_of_death %}{{ author.date_of_death }}{% endif %}</p>
	<div style="margin-left:20px;margin-top:20px">
		<h4>Books</h4>

		<dl>
			{% for book in author.book_set.all %}
				<dt><a href="{% url 'book-detail' book.pk %}">{{ book }}</a> ({{ book.bookinstance_set.all.count }})
				</dt>
				<dd>{{ book.summary }}</dd>
			{% endfor %}
		</dl>
	</div>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block title %}
	<title>List of Authors</title>
{% endblock %}

{% block content %}
	<h1>Author List</h1>
	{% if author_list %}
		<ul>
			{% for author in author_list %}
				<li>
					<a href="{{ author.get_absolute_url }}">{{ author }}</a>
				</li>
			{% endfor %}
		</ul>
	{% else %}
		<p>There are no authors in the library.</p>
	{% endif %}
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block title %}
	<title>Book detail</title>
{% endblock %}

{% block content %}
	<h1>{{ book.title }}</h1>

	{#	<p><strong>Author:</strong> <a href="{% url 'author-detail'  book.author.pk %}">{{ book.author }}</a></p>#}
	<p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p>
	<p><strong>Summary:</strong> {{ book.summary }}</p>
	<p><strong>ISBN:</strong> {{ book.isbn }}</p>
	<p><strong>Language:</strong> {{ book.language }}</p>
	<p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

	<div style="margin-left:20px;margin-top:20px">
		<h4>Copies</h4>

		{% for copy in book.bookinstance_set.all %}
			<hr>
			<p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
				{{ copy.get_status_display }}
			</p>
			{% if copy.status != 'a' %}
				<p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
			{% endif %}
			<p><strong>Imprint:</strong> {{ copy.imprint }}</p>
			<p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
		{% endfor %}
	</div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block title %}
	<title>List of books</title>
{% endblock %}

{% block content %}
	<h1>Book List</h1>
	{% if book_list %}
		<ul>
			{% for book in book_list %}
				<li>
					<a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ~ <em>{{ book.author }}</em>
				</li>
			{% endfor %}
		</ul>
	{% else %}
		<p>There are no books in the library.</p>
	{% endif %}
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_all.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All Borrowed Books</h1>
    {% if bookinstance_list %}
        <ul>
            {% for bookinst in bookinstance_list %}
                <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
                    <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a>
                    ({{ bookinst.due_back }}) {% if user.is_staff %}- {{ bookinst.borrower }}{% endif %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
        <ul>
            {% for bookinst in bookinstance_list %}
                <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
                    <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a>
                    ({{ bookinst.due_back }})
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>You haven't borrowed any books. Try borrowing some, we'll show them up here.</p>
    {% endif %}
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block title %}
	<title>Home | Minimal Library</title>
{% endblock %}

{% block content %}
	<h1>Minimal Library Home</h1>
	<p>Welcome to <strong>Minimal Library</strong>, built with <em>Django</em>!</p>
	<h2>Library Record</h2>
	<p>The library has the following record counts:</p>
	<ul>
		<li><strong>Books:</strong> {{ num_books }}</li>
		<li><strong>Copies:</strong> {{ num_instances }}</li>
		<li><strong>Copies available:</strong> {{ num_instances_available }}</li>
		<li><strong>Authors:</strong> {{ num_authors }}</li>
	</ul>
{% endblock %}